$(document).ready(function() {
	var nav = "<a class='navbar-brand' href='index.html''>RTS</a>"
        +"<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarsExample07' aria-controls='navbarsExample07' aria-expanded='false' aria-label='Toggle navigation'>"
          +"<span class='navbar-toggler-icon'></span>"
        +"</button>"
        +"<div class='collapse navbar-collapse' id='navbarsExample07'>"
          +"<ul class='navbar-nav mr-auto'>"
            +"<li class='nav-item'>"
              +"<a class='nav-link' href='jurnalumum.html'>Jurnal Umum</a>"
            +"</li>"
            +"<li class='nav-item'>"
              +"<a class='nav-link' href='riwayat_akun.html'>Riwayat Akun</a>"
            +"</li>"
            +"<li class='nav-item dropdown'>"
              +"<a class='nav-link dropdown-toggle' href='http://example.com' id='dropdown07' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>Data Akun</a>"
              +"<div class='dropdown-menu' aria-labelledby='dropdown07'>"
                +"<a class='dropdown-item' href='akunheader.html'>Akun Header</a>"
                +"<a class='dropdown-item' href='akundetail.html'>Akun Detail</a>"
              +"</div>"
            +"</li>"
            +"<li class='nav-item dropdown'>"
              +"<a class='nav-link dropdown-toggle' href='#' id='dropdown07' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>Alat</a>"
              +"<div class='dropdown-menu' aria-labelledby='dropdown07'>"
                +"<a class='dropdown-item' href='info.html'>Informasi Persuhaan</a>"
                +"<a class='dropdown-item' href='datapengguna.html'>Data Pengguna</a>"
                +"<a class='dropdown-item' href='gantipass.html'>Ganti Password</a>"
              +"</div>"
            +"</li>"
            +"<li class='nav-item'>"
                +"<a class='nav-link' href='login.html'>Keluar</a>"
            +"</li>"
          +"</ul>"
        +"</div>";

	$("#nav").html(nav);
});